# This file was generated by GoReleaser. DO NOT EDIT.
cask "crucible" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "28cf5d154b6bd027f634af38f0c6879b81575ffbe040c29f22abfd97c6249bb2"
      url "https://github.com/adiwidia-dev/crucible-db/releases/download/v#{version}/crucible_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c763583b75f8e8f866596bbb215cb370d32cb2ea6bc34ae0dfa1d0d3581f1a18"
      url "https://github.com/adiwidia-dev/crucible-db/releases/download/v#{version}/crucible_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "dc8451c42020c53166fc74b90de67f3e126104aac47874bf7ff33be47a630b31"
      url "https://github.com/adiwidia-dev/crucible-db/releases/download/v#{version}/crucible_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "0b6ec34f417c97466f78336fa5e71c2ff4f7f0f1ef60643fe725627ce173be15"
      url "https://github.com/adiwidia-dev/crucible-db/releases/download/v#{version}/crucible_#{version}_linux_amd64.tar.gz"
    end
  end

  name "crucible"
  desc "Governed native database-client access for Crucible DB."
  homepage "https://github.com/adiwidia-dev/crucible-db"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crucible"

  # No zap stanza required
end
