# This file was generated by GoReleaser. DO NOT EDIT.
cask "crucible" do
  version "0.2.5"

  on_macos do
    on_arm do
      sha256 "f441105e957ab0982c8d84aebeb0cdd8941714f02ed5c290425ea064789c7f80"
      url "https://github.com/adiwidia-dev/crucible-db/releases/download/v#{version}/crucible_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "256250379a3b104cbd72bc822632d808e8fdd9bbb9d8b26459664d133442a9c0"
      url "https://github.com/adiwidia-dev/crucible-db/releases/download/v#{version}/crucible_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e3d6248e20b3ec7909fa69bb7f73d956db9b904f12151cbdce64b5e908104b37"
      url "https://github.com/adiwidia-dev/crucible-db/releases/download/v#{version}/crucible_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1499305f6cb0ed91496a50bab2067f0ffd994992db9561507ef01e230f641acb"
      url "https://github.com/adiwidia-dev/crucible-db/releases/download/v#{version}/crucible_#{version}_linux_amd64.tar.gz"
    end
  end

  name "crucible"
  desc "Governed native database-client access for Crucible DB."
  homepage "https://github.com/adiwidia-dev/crucible-db"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crucible"

  # No zap stanza required
end
