# This file was generated by GoReleaser. DO NOT EDIT.
cask "crucible" do
  version "0.2.2"

  on_macos do
    on_arm do
      sha256 "d7314c1f4f230ed17a964a669c7fc5e04a9bd83373682c728b12759b8c68e531"
      url "https://github.com/adiwidia-dev/crucible-db/releases/download/v#{version}/crucible_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cdd6699d8de21b9e2b0089c5c3d2cb1f9c0a123300b1d6e3b2c43bede920b8a3"
      url "https://github.com/adiwidia-dev/crucible-db/releases/download/v#{version}/crucible_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7dff322cdaf1766ee0dc194eda4c54546da6d3292662e9dc577f396ffaa7d938"
      url "https://github.com/adiwidia-dev/crucible-db/releases/download/v#{version}/crucible_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d53ac34abbc28c9800190c3dd35981b403c3fdeece7e195c1dcb9c0d67ac2f2b"
      url "https://github.com/adiwidia-dev/crucible-db/releases/download/v#{version}/crucible_#{version}_linux_amd64.tar.gz"
    end
  end

  name "crucible"
  desc "Governed native database-client access for Crucible DB."
  homepage "https://github.com/adiwidia-dev/crucible-db"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crucible"

  # No zap stanza required
end
